name       : mozc
version    : 2.29.5150.102
release    : 11
source     :
    - git|https://github.com/fcitx/mozc.git : 0049ee3a8ceb03144b4521e559449f2a7da34f42
    - https://download.fcitx-im.org/fcitx-mozc/fcitx-mozc-icon.tar.gz : e1da3026bd79f8c5b1dc07080309f9568934a829271f4ab71850cb8088956d81
homepage   : https://github.com/fcitx/mozc
license    : BSD-3-Clause
component  :
    - desktop.core
    - ^fcitx-mozc : desktop.core
    - ^ibus-mozc : desktop.core
summary    :
    - Japanese Input Method for Linux
    - ^fcitx-mozc : Mozc engine for Fcitx
    - ^ibus-mozc : Mozc engine for IBus
description: |
    Mozc is a Japanese Input Method Editor (IME) for Linux that provides support for Fcitx or IBus.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(absl_base)
    - pkgconfig(fcitx)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(protobuf)
    - pkgconfig(xcb)
    - pkgconfig(zinnia)
    - llvm-clang
rundeps    :
    - ^fcitx-mozc :
        - fcitx
        - mozc
    - ^ibus-mozc :
        - mozc
setup      : |
    %apply_patches

    rm -rf src/unix/fcitx5
    pushd ..
    tar xf $sources/fcitx-mozc-icon.tar.gz
    popd

    rm -rf src/third_party/abseil-cpp

    GYP_DEFINES="ibus_mozc_path=/usr/lib64/ibus-mozc/ibus-engine-mozc \
        use_libprotobuf=1 \
        use_libzinnia=1 \
        use_system_abseil_cpp=1" \
    python3 src/build_mozc.py gyp --server_dir=/usr/lib64/mozc --target_platform=Linux
build      : |
    targets="
        unix/ibus/ibus.gyp:ibus_mozc
        unix/fcitx/fcitx.gyp:fcitx-mozc
        server/server.gyp:mozc_server
        gui/gui.gyp:mozc_tool
        renderer/renderer.gyp:mozc_renderer"
    python3 src/build_mozc.py build -c Release $targets
install    : |
    pushd src
    install -d $installdir/usr/lib/{mozc,fcitx}
    pushd out_linux/Release
    install -Dm00755 mozc_server $installdir/usr/lib/mozc
    install -Dm00755 mozc_tool $installdir/usr/lib/mozc
    install -Dm00644 fcitx-mozc.so $installdir/usr/lib/fcitx
    mv ibus_mozc ibus-engine-mozc
    for bin in ibus-engine-mozc; do
        install -Dm00755 $bin $installdir/usr/lib/ibus-mozc/$bin
    done
    for bin in mozc_renderer mozc_server mozc_tool; do
        install -Dm00755 $bin $installdir/usr/lib/mozc/$bin
    done
    for xml in gen/unix/ibus/mozc.xml; do
        install -Dm00644 $xml $installdir/usr/share/ibus/component/${xml##*/}
    done
    popd
    pushd data/images/unix
    cp ime_product_icon_opensource-32.png product_icon.png
    for icon in *.png; do
        install -Dm00644 $icon $installdir/usr/share/ibus-mozc/${icon#ui-}
    done
    popd
    install -Dm00644 unix/fcitx/fcitx-mozc.conf $installdir/usr/share/fcitx/addon/fcitx-mozc.conf
    install -Dm00644 unix/fcitx/mozc.conf $installdir/usr/share/fcitx/inputmethod/mozc.conf

    for dotmo in out_linux/Release/gen/unix/fcitx/po/*.mo; do
        filename=$(basename $dotmo)
        lang=${filename/.mo/}
        install -Dm00644 $dotmo $installdir/usr/share/locale/$lang/LC_MESSAGES/fcitx-mozc.mo
    done
    popd

    pushd ..
    install -d $installdir/usr/share/fcitx/mozc/icon
    install -m00644 fcitx-mozc-icons/mozc.png $installdir/usr/share/fcitx/mozc/icon/mozc.png
    install -m00644 fcitx-mozc-icons/mozc-alpha_full.png $installdir/usr/share/fcitx/mozc/icon/mozc-alpha_full.png
    install -m00644 fcitx-mozc-icons/mozc-alpha_half.png $installdir/usr/share/fcitx/mozc/icon/mozc-alpha_half.png
    install -m00644 fcitx-mozc-icons/mozc-direct.png $installdir/usr/share/fcitx/mozc/icon/mozc-direct.png
    install -m00644 fcitx-mozc-icons/mozc-hiragana.png $installdir/usr/share/fcitx/mozc/icon/mozc-hiragana.png
    install -m00644 fcitx-mozc-icons/mozc-katakana_full.png $installdir/usr/share/fcitx/mozc/icon/mozc-katakana_full.png
    install -m00644 fcitx-mozc-icons/mozc-katakana_half.png $installdir/usr/share/fcitx/mozc/icon/mozc-katakana_half.png
    install -m00644 fcitx-mozc-icons/mozc-dictionary.png $installdir/usr/share/fcitx/mozc/icon/mozc-dictionary.png
    install -m00644 fcitx-mozc-icons/mozc-properties.png $installdir/usr/share/fcitx/mozc/icon/mozc-properties.png
    install -m00644 fcitx-mozc-icons/mozc-tool.png $installdir/usr/share/fcitx/mozc/icon/mozc-tool.png
patterns   :
    - ^fcitx-mozc :
        - /usr/lib/fcitx
        - /usr/share/fcitx
    - ^ibus-mozc :
        - /usr/lib/ibus-mozc
        - /usr/share/ibus
