name       : cockatrice
version    : 2.9.0
release    : 23
source     :
    - https://github.com/Cockatrice/Cockatrice/archive/refs/tags/2023-09-14-Release-2.9.0.tar.gz : c40207c00b288e7c296bc21dc320dfa2f4e79936bb22799146c23963f82dae82
homepage   : https://cockatrice.github.io/
license    : GPL-2.0-or-later
component  : games.card
summary    : A cross-platform virtual tabletop for multiplayer card games
description: |
    Cockatrice is an open-source multiplatform software for playing card games, such as Magic: The Gathering, over a network. It is fully client-server based to prevent any kind of cheating, though it supports single-player games without a network interface as well. Both client and server are written in Qt, supporting both Qt4 and Qt5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(liblzma)
    - pkgconfig(protobuf)
rundeps    :
    - wget
setup      : |
    %patch -p1 -i $pkgfiles/protobuf-23.patch

    %cmake_ninja -DWITH_SERVER=1
build      : |
    %ninja_build
install    : |
    %ninja_install

    # appstream data
    install -Dm00644 $pkgfiles/io.github.Cockatrice.appdata.xml $installdir/usr/share/metainfo/io.github.Cockatrice.appdata.xml
    # rename desktop file to match appstream desktop-id
    mv $installdir/usr/share/applications/{cockatrice,io.github.Cockatrice.cockatrice}.desktop
