name       : mumble
version    : 1.5.634
release    : 40
source     :
    - https://github.com/mumble-voip/mumble/releases/download/v1.5.634/mumble-1.5.634.tar.gz : 904f3633d28ab0e6925caeff2c65802f586abefdf6d20162f20a71805c2c5929
homepage   : https://www.mumble.info
license    : BSD-3-Clause
component  : network.clients
summary    : High quality voice chat software
description: |
    Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(harfbuzz)
    - pkgconfig(libcap)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(nlohmann_json)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(xi)
    - libboost-devel
    - microsoft-gsl
    - poco-devel
setup      : |
    %cmake_ninja \
        -Dbundle-qt-translations=OFF \
        -Dbundled-gsl=OFF \
        -Dbundled-json=OFF \
        -Dbundled-renamenoise=ON \
        -Dbundled-speex=OFF \
        -Dice=OFF \
        -Doverlay-xcompile=OFF \
        -Dserver=OFF \
        -Dspeechd=OFF \
        -Dupdate=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
