name       : python-sentry-sdk
version    : 2.11.0
release    : 3
source     :
    - https://pypi.debian.net/sentry-sdk/sentry_sdk-2.11.0.tar.gz : 4ca16e9f5c7c6bc2fb2d5c956219f4926b148e511fffdbbde711dc94f1e0468f
license    : MIT
component  : programming.python
homepage   : https://sentry.io/for/python
summary    : The official Python SDK for Sentry.io
description: |
    The official Python SDK for Sentry.io
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-certifi
    - python-urllib3
build      : |
    %python3_setup
install    : |
    %python3_install
