name       : protobuf-c
version    : 1.5.0
release    : 12
source     :
    - https://github.com/protobuf-c/protobuf-c/releases/download/v1.5.0/protobuf-c-1.5.0.tar.gz : 7b404c63361ed35b3667aec75cc37b54298d56dd2bcf369de3373212cc06fd98
homepage   : https://github.com/protobuf-c/protobuf-c
license    : BSD-2-Clause
component  : programming.library
summary    : Protocol Buffers implementation in C
description: |
    This is protobuf-c, a C implementation of the Google Protocol. Buffers data serialization format. It includes libprotobuf-c, a pure C library that implements protobuf encoding and decoding, and protoc-c,  a code generator that converts Protocol Buffer .proto files to C descriptor code, based on the original protoc. protobuf-c formerly included an RPC implementation; that code has been split out into the protobuf-c-rpc project.
builddeps  :
    - pkgconfig(protobuf)
setup      : |
    %patch -p1 -i $pkgfiles/protobuf-26.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
