name       : marble
version    : 24.05.2
release    : 88
source     :
    - https://download.kde.org/stable/release-service/24.05.2/src/marble-24.05.2.tar.xz : 80a727bba2f5e88975ddf78b41d969bb0ac93cf6447924db3363ccd2e25a3f82
homepage   : https://kde.org/applications/education/org.kde.marble
license    : LGPL-2.1-or-later
component  :
    - network.web
    - libs : programming.library
summary    : Virtual Globe and World Atlas
description: |
    Marble is a Virtual Globe and World Atlas that you can use to learn more about Earth: You can pan and zoom around and you can look up places and roads.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - kcoreaddons-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    # - krunner-devel
    - kwallet-devel
    - plasma-framework-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DBUILD_MARBLE_TOOLS=YES \
               -DBUILD_MARBLE_TESTS=OFF \
               -DBUILD_TOUCH=ON \
               -DMOBILE=OFF \
               -DQT_PLUGINS_DIR=lib64/qt5/plugins
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove docs
    rm -rfv $installdir/usr/share/doc

    # Not compatible with Plasma 6. Bring back once ported to Qt6
    rm -rfv $installdir/usr/share/plasma/plasmoids \
            $installdir/usr/share/kservices5/plasma*.desktop
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
        - /usr/lib64/libmarbledeclarative.so
        - /usr/lib64/marble/plugins
