name       : telegram
version    : 5.2.2
release    : 216
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v5.2.2/tdesktop-5.2.2-full.tar.gz : 8c278aae061a9461459a09fe0139854027182a4bec6d706d0f4fb9df9b303e3e
    - git|https://github.com/desktop-app/tg_owt.git : 3bb3d757681e6cc5135aec6529a753dc3dcdcfb9
homepage   : https://desktop.telegram.org/
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram Desktop messaging app
description: |
    Telegram is a messaging app with a focus on speed and security, it's super fast, simple and free.
optimize   :
    - function-sections
    # Temporarily disabled due to Clang 16 build issue
    # - icf-safe
    # - thin-lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(alsa)
    - pkgconfig(epoxy)
    - pkgconfig(fmt)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libavif)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    # TODO Fix minizip-ng compat
    # - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(protobuf) # For the bundles cdl3 library.
    - pkgconfig(rnnoise)
    - pkgconfig(vpx)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - gobject-introspection
    - kf6-kcoreaddons-devel
    - kf6-kimageformats
    - libboost-devel
    - libdispatch-devel
    - plasma-wayland-protocols
    - yasm
rundeps    :
    - qt6-imageformats
# Temporarily disabled due to Clang 16 build issue
# clang      : yes
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %patch -p1 -i $pkgfiles/tg_owt-clang12.patch
        %cmake_ninja -DTG_OWT_DLOPEN_PIPEWIRE=OFF
        %ninja_build
    popd

    # Building with -O2 and any variant of LTO seems to cause segfaults during notifications. -O2 is the default for RelWithDebInfo so
    # we need to set the cmake build to None and add the flags manually. It's really weird that -O3 works fine and -O2 doesn't...
    export CXXFLAGS="$CXXFLAGS -O3 -DNDEBUG"

    # Force build against minizip-ng
    # sed -i "s|minizip<2.0.0|minizip|" cmake/external/minizip/CMakeLists.txt
    # pushd Telegram/lib_base
    # %patch -p1 -i $pkgfiles/0001-Fix-build-with-minizip-ng.patch
    # popd

    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_DISABLE_JEMALLOC=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
