name       : strawberry
version    : 1.1.1
release    : 62
source     :
    - https://github.com/strawberrymusicplayer/strawberry/releases/download/1.1.1/strawberry-1.1.1.tar.xz : ec0deff3c332aaa79dc9fb6dddd694480695cc6c97e7a7aba48e45cdde11f302
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libebur128)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - kdsingleapplication-devel
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja -DINSTALL_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
